module SkelVarlang where

-- Haskell module generated by the BNF converter

import AbsVarlang
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Program stms -> failure x
transArg :: Arg -> Result
transArg x = case x of
  Arg type_ ident -> failure x
transDecl :: Decl -> Result
transDecl x = case x of
  Decl type_ idents -> failure x
transStm :: Stm -> Result
transStm x = case x of
  StmDecl decl -> failure x
  StmBlock stms -> failure x
  StmAss ident exp -> failure x
  StmDictAss ident exp1 exp2 -> failure x
  StmStepExp exp -> failure x
  StmIf exp stm -> failure x
  StmIfElse exp stm1 stm2 -> failure x
  StmWhile exp stm -> failure x
  StmFor decl exp stms -> failure x
  StmFunDef ident args stms -> failure x
  RetStm exp -> failure x
  RetVoidStm -> failure x
  StmMatch exp casestms -> failure x
  StmPrint exp -> failure x
  StmPrintS string -> failure x
transCaseStm :: CaseStm -> Result
transCaseStm x = case x of
  CaseStm ident1 ident2 stms -> failure x
transType :: Type -> Result
transType x = case x of
  Int -> failure x
  Bool -> failure x
  Char -> failure x
  Void -> failure x
  Fun type_ types -> failure x
  List type_ -> failure x
  Dict type_1 type_2 -> failure x
  Var vards -> failure x
transVarD :: VarD -> Result
transVarD x = case x of
  VarD ident type_ -> failure x
transEDictD :: EDictD -> Result
transEDictD x = case x of
  EDictD exp1 exp2 -> failure x
transExp :: Exp -> Result
transExp x = case x of
  EIncrR ident -> failure x
  EIncr ident -> failure x
  EDecrR ident -> failure x
  EDecr ident -> failure x
  EIncrExp ident exp -> failure x
  EDecrExp ident exp -> failure x
  EDivExp ident exp -> failure x
  EMulrExp ident exp -> failure x
  EModrExp ident exp -> failure x
  EVariable ident -> failure x
  EInt integer -> failure x
  EChar char -> failure x
  EValTrue -> failure x
  EValFalse -> failure x
  EList exps -> failure x
  EVar ident exp -> failure x
  EFun args stms -> failure x
  EFunCall ident exps -> failure x
  EDict edictds -> failure x
  EDictGet ident exp -> failure x
  EVarIs exp ident -> failure x
  ENeg exp -> failure x
  ENot exp -> failure x
  EMul exp1 exp2 -> failure x
  EDiv exp1 exp2 -> failure x
  EMod exp1 exp2 -> failure x
  EAdd exp1 exp2 -> failure x
  ESub exp1 exp2 -> failure x
  ELTH exp1 exp2 -> failure x
  ELE exp1 exp2 -> failure x
  EGTH exp1 exp2 -> failure x
  EGE exp1 exp2 -> failure x
  EEQU exp1 exp2 -> failure x
  ENE exp1 exp2 -> failure x
  EAnd exp1 exp2 -> failure x
  EOr exp1 exp2 -> failure x

